// import type { Metadata } from "next";
import { Nunito, Inter } from "next/font/google";
import "../app/globals.css";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Matthew Bachelder | Portfolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col h-screen justify-between antialiased ${nunito.variable} ${inter.variable}`}>
        <Navbar />
        <main className="mb-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
